// Mocks generated by Mockito 5.4.6 from annotations
// in foodathon/test/providers/order_provider_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i4;

import 'package:foodathon/models/order.dart' as _i2;
import 'package:foodathon/models/order_item.dart' as _i5;
import 'package:foodathon/repositories/order_repository.dart' as _i3;
import 'package:mockito/mockito.dart' as _i1;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class
// ignore_for_file: invalid_use_of_internal_member

class _FakeOrder_0 extends _i1.SmartFake implements _i2.Order {
  _FakeOrder_0(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

/// A class which mocks [OrderRepository].
///
/// See the documentation for Mockito's code generation for more information.
class MockOrderRepository extends _i1.Mock implements _i3.OrderRepository {
  MockOrderRepository() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i4.Future<_i2.Order> createOrder({
    required String? customerId,
    required String? customerName,
    required String? restaurantId,
    required String? restaurantName,
    required List<_i5.OrderItem>? items,
    required double? total,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#createOrder, [], {
              #customerId: customerId,
              #customerName: customerName,
              #restaurantId: restaurantId,
              #restaurantName: restaurantName,
              #items: items,
              #total: total,
            }),
            returnValue: _i4.Future<_i2.Order>.value(
              _FakeOrder_0(
                this,
                Invocation.method(#createOrder, [], {
                  #customerId: customerId,
                  #customerName: customerName,
                  #restaurantId: restaurantId,
                  #restaurantName: restaurantName,
                  #items: items,
                  #total: total,
                }),
              ),
            ),
          )
          as _i4.Future<_i2.Order>);

  @override
  _i4.Future<_i2.Order?> fetchOrder(String? orderId) =>
      (super.noSuchMethod(
            Invocation.method(#fetchOrder, [orderId]),
            returnValue: _i4.Future<_i2.Order?>.value(),
          )
          as _i4.Future<_i2.Order?>);

  @override
  _i4.Future<void> updateOrderStatus({
    required String? orderId,
    required _i2.OrderStatus? status,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#updateOrderStatus, [], {
              #orderId: orderId,
              #status: status,
            }),
            returnValue: _i4.Future<void>.value(),
            returnValueForMissingStub: _i4.Future<void>.value(),
          )
          as _i4.Future<void>);

  @override
  _i4.Future<void> assignRunner({
    required String? orderId,
    required String? runnerId,
    double? distanceToRestaurant,
    double? distanceToCustomer,
    double? commission,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#assignRunner, [], {
              #orderId: orderId,
              #runnerId: runnerId,
              #distanceToRestaurant: distanceToRestaurant,
              #distanceToCustomer: distanceToCustomer,
              #commission: commission,
            }),
            returnValue: _i4.Future<void>.value(),
            returnValueForMissingStub: _i4.Future<void>.value(),
          )
          as _i4.Future<void>);

  @override
  _i4.Future<void> cancelOrder(String? orderId) =>
      (super.noSuchMethod(
            Invocation.method(#cancelOrder, [orderId]),
            returnValue: _i4.Future<void>.value(),
            returnValueForMissingStub: _i4.Future<void>.value(),
          )
          as _i4.Future<void>);

  @override
  _i4.Stream<_i2.Order?> streamOrder(String? orderId) =>
      (super.noSuchMethod(
            Invocation.method(#streamOrder, [orderId]),
            returnValue: _i4.Stream<_i2.Order?>.empty(),
          )
          as _i4.Stream<_i2.Order?>);

  @override
  _i4.Stream<List<_i2.Order>> streamCustomerOrders(String? customerId) =>
      (super.noSuchMethod(
            Invocation.method(#streamCustomerOrders, [customerId]),
            returnValue: _i4.Stream<List<_i2.Order>>.empty(),
          )
          as _i4.Stream<List<_i2.Order>>);

  @override
  _i4.Stream<List<_i2.Order>> streamRestaurantOrders(String? restaurantId) =>
      (super.noSuchMethod(
            Invocation.method(#streamRestaurantOrders, [restaurantId]),
            returnValue: _i4.Stream<List<_i2.Order>>.empty(),
          )
          as _i4.Stream<List<_i2.Order>>);

  @override
  _i4.Stream<List<_i2.Order>> streamAvailableOrders() =>
      (super.noSuchMethod(
            Invocation.method(#streamAvailableOrders, []),
            returnValue: _i4.Stream<List<_i2.Order>>.empty(),
          )
          as _i4.Stream<List<_i2.Order>>);

  @override
  _i4.Future<List<_i2.Order>> fetchCustomerOrders(String? customerId) =>
      (super.noSuchMethod(
            Invocation.method(#fetchCustomerOrders, [customerId]),
            returnValue: _i4.Future<List<_i2.Order>>.value(<_i2.Order>[]),
          )
          as _i4.Future<List<_i2.Order>>);
}
