name: foodathon
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0+1

environment:
  sdk: ^3.11.3

dependencies:
  cached_network_image: ^3.4.1
  cloud_firestore: ^6.3.0
  equatable: ^2.0.8
  firebase_app_check: ^0.4.3
  firebase_auth: ^6.4.0
  firebase_core: ^4.7.0
  firebase_messaging: ^16.2.0
  firebase_storage: ^13.3.0
  flutter:
    sdk: flutter
  geolocator: ^14.0.2
  google_maps_flutter: ^2.17.0
  image_picker: ^1.2.1
  intl: ^0.20.2
  json_annotation: ^4.11.0
  logger: ^2.7.0
  permission_handler: ^12.0.1
  provider: ^6.1.5+1
  uuid: ^4.5.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  build_runner: ^2.14.1
  json_serializable: ^6.13.1
  mockito: ^5.4.0

flutter:
  uses-material-design: true
