import '../models/restaurant.dart';

const List<Restaurant> mockRestaurants = [
  Restaurant(
    id: 'rest-1',
    ownerId: 'owner-1',
    name: 'Bella Napoli',
    description: 'Authentic wood-fired pizzas and handmade pastas from family recipes passed down through generations.',
    cuisine: 'Italian',
    priceLevel: 2,
    rating: 4.7,
  ),
  Restaurant(
    id: 'rest-2',
    ownerId: 'owner-2',
    name: 'El Camino Taqueria',
    description: 'Street-style tacos, fresh salsas, and slow-cooked meats served with handmade tortillas.',
    cuisine: 'Mexican',
    priceLevel: 1,
    rating: 4.5,
  ),
  Restaurant(
    id: 'rest-3',
    ownerId: 'owner-3',
    name: 'Sakura House',
    description: 'Premium sushi and ramen crafted with imported ingredients and traditional Japanese techniques.',
    cuisine: 'Japanese',
    priceLevel: 3,
    rating: 4.8,
  ),
  Restaurant(
    id: 'rest-4',
    ownerId: 'owner-4',
    name: 'Curry Kingdom',
    description: 'Rich curries, fluffy naan, and aromatic biryanis made with freshly ground spices.',
    cuisine: 'Indian',
    priceLevel: 2,
    rating: 4.4,
  ),
  Restaurant(
    id: 'rest-5',
    ownerId: 'owner-5',
    name: 'Smokehouse BBQ',
    description: 'Low-and-slow smoked brisket, ribs, and pulled pork with signature house-made sauces.',
    cuisine: 'American',
    priceLevel: 2,
    rating: 4.6,
  ),
  Restaurant(
    id: 'rest-6',
    ownerId: 'owner-6',
    name: 'Bangkok Bites',
    description: 'Vibrant Thai curries, stir-fries, and noodle dishes with bold and balanced flavors.',
    cuisine: 'Thai',
    priceLevel: 1,
    rating: 4.3,
  ),
];
