import '../models/order.dart';
import '../models/order_item.dart';

const String mockRestaurantName = 'Bella Napoli';

final List<Order> mockRestaurantOrders = [
  Order(
    id: 'rest-order-1',
    customerId: 'cust-1',
    customerName: 'Alice Johnson',
    restaurantId: 'rest-1',
    restaurantName: mockRestaurantName,
    items: const [
      OrderItem(menuItemId: 'bn-1', name: 'Margherita Pizza', quantity: 1, price: 14.99),
      OrderItem(menuItemId: 'bn-4', name: 'Tiramisu', quantity: 2, price: 7.99),
    ],
    status: OrderStatus.sent,
    total: 30.97,
    createdAt: DateTime(2026, 4, 29, 12, 0),
  ),
  Order(
    id: 'rest-order-2',
    customerId: 'cust-2',
    customerName: 'Bob Smith',
    restaurantId: 'rest-1',
    restaurantName: mockRestaurantName,
    items: const [
      OrderItem(menuItemId: 'bn-1', name: 'Pepperoni Pizza', quantity: 1, price: 16.99),
      OrderItem(menuItemId: 'bn-3', name: 'Garlic Bread', quantity: 1, price: 5.99),
    ],
    status: OrderStatus.sent,
    total: 22.98,
    createdAt: DateTime(2026, 4, 29, 12, 5),
  ),
  Order(
    id: 'rest-order-3',
    customerId: 'cust-3',
    customerName: 'Carol Davis',
    restaurantId: 'rest-1',
    restaurantName: mockRestaurantName,
    items: const [
      OrderItem(menuItemId: 'bn-2', name: 'Lasagna', quantity: 1, price: 18.99),
    ],
    status: OrderStatus.confirmed,
    total: 18.99,
    createdAt: DateTime(2026, 4, 29, 11, 45),
  ),
  Order(
    id: 'rest-order-4',
    customerId: 'cust-4',
    customerName: 'Dan Wilson',
    restaurantId: 'rest-1',
    restaurantName: mockRestaurantName,
    items: const [
      OrderItem(menuItemId: 'bn-3', name: 'Caprese Salad', quantity: 1, price: 12.99),
      OrderItem(menuItemId: 'bn-2', name: 'Spaghetti Carbonara', quantity: 1, price: 15.99),
      OrderItem(menuItemId: 'bn-4', name: 'Tiramisu', quantity: 1, price: 7.99),
    ],
    status: OrderStatus.confirmed,
    total: 36.97,
    createdAt: DateTime(2026, 4, 29, 11, 30),
  ),
  Order(
    id: 'rest-order-5',
    customerId: 'cust-5',
    customerName: 'Eve Martinez',
    restaurantId: 'rest-1',
    restaurantName: mockRestaurantName,
    items: const [
      OrderItem(menuItemId: 'bn-3', name: 'Bruschetta', quantity: 2, price: 9.99),
    ],
    status: OrderStatus.readyForPickup,
    total: 19.98,
    createdAt: DateTime(2026, 4, 29, 11, 15),
  ),
];

final List<Order> mockOrders = [
  Order(
    id: 'order-1',
    customerId: 'cust-1',
    customerName: 'Alice Johnson',
    restaurantId: 'rest-1',
    restaurantName: 'Bella Napoli',
    items: const [
      OrderItem(menuItemId: 'bn-1', name: 'Margherita Pizza', quantity: 1, price: 14.99),
      OrderItem(menuItemId: 'bn-4', name: 'Tiramisu', quantity: 2, price: 7.99),
    ],
    status: OrderStatus.confirmed,
    distanceToRestaurant: 1.2,
    distanceToCustomer: 2.5,
    commission: 10.00,
    total: 30.97,
    createdAt: DateTime(2026, 4, 29, 12, 0),
  ),
  Order(
    id: 'order-2',
    customerId: 'cust-2',
    customerName: 'Bob Smith',
    restaurantId: 'rest-2',
    restaurantName: 'El Camino Taqueria',
    items: const [
      OrderItem(menuItemId: 'ec-1', name: 'Street Tacos', quantity: 3, price: 4.50),
      OrderItem(menuItemId: 'ec-4', name: 'Churros', quantity: 1, price: 5.99),
    ],
    status: OrderStatus.confirmed,
    distanceToRestaurant: 0.8,
    distanceToCustomer: 1.7,
    commission: 10.00,
    total: 19.49,
    createdAt: DateTime(2026, 4, 29, 12, 10),
  ),
  Order(
    id: 'order-3',
    customerId: 'cust-3',
    customerName: 'Carol Davis',
    restaurantId: 'rest-3',
    restaurantName: 'Sakura House',
    items: const [
      OrderItem(menuItemId: 'sh-3', name: 'Dragon Roll', quantity: 2, price: 16.99),
      OrderItem(menuItemId: 'sh-4', name: 'Miso Soup', quantity: 1, price: 4.50),
    ],
    status: OrderStatus.confirmed,
    distanceToRestaurant: 2.1,
    distanceToCustomer: 3.0,
    commission: 10.00,
    total: 38.48,
    createdAt: DateTime(2026, 4, 29, 12, 15),
  ),
  Order(
    id: 'order-4',
    customerId: 'cust-4',
    customerName: 'Dan Wilson',
    restaurantId: 'rest-4',
    restaurantName: 'Curry Kingdom',
    items: const [
      OrderItem(menuItemId: 'ck-1', name: 'Butter Chicken', quantity: 1, price: 15.99),
      OrderItem(menuItemId: 'ck-2', name: 'Garlic Naan', quantity: 2, price: 3.99),
    ],
    status: OrderStatus.confirmed,
    distanceToRestaurant: 0.5,
    distanceToCustomer: 1.3,
    commission: 10.00,
    total: 23.97,
    createdAt: DateTime(2026, 4, 29, 12, 20),
  ),
  Order(
    id: 'order-5',
    customerId: 'cust-5',
    customerName: 'Eve Martinez',
    restaurantId: 'rest-5',
    restaurantName: 'Smokehouse BBQ',
    items: const [
      OrderItem(menuItemId: 'sb-1', name: 'Brisket Plate', quantity: 1, price: 18.99),
      OrderItem(menuItemId: 'sb-4', name: 'Coleslaw', quantity: 1, price: 4.50),
    ],
    status: OrderStatus.confirmed,
    distanceToRestaurant: 1.8,
    distanceToCustomer: 2.2,
    commission: 10.00,
    total: 23.49,
    createdAt: DateTime(2026, 4, 29, 12, 25),
  ),
  Order(
    id: 'order-6',
    customerId: 'cust-6',
    customerName: 'Frank Lee',
    restaurantId: 'rest-6',
    restaurantName: 'Bangkok Bites',
    items: const [
      OrderItem(menuItemId: 'bb-1', name: 'Pad Thai', quantity: 2, price: 13.99),
      OrderItem(menuItemId: 'bb-3', name: 'Spring Rolls', quantity: 1, price: 6.99),
    ],
    status: OrderStatus.confirmed,
    distanceToRestaurant: 0.3,
    distanceToCustomer: 1.9,
    commission: 10.00,
    total: 34.97,
    createdAt: DateTime(2026, 4, 29, 12, 30),
  ),
];
